exclude: ^.idea/|.vscode/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.14
    hooks:
      - id: uv-lock
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.3
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
      - id: check-readthedocs
  - repo: https://github.com/adhtruong/mirrors-typos
    # See https://github.com/crate-ci/typos/issues/390
    # repo: https://github.com/crate-ci/typos
    rev: v1.36.0
    hooks:
      - id: typos
        args: [--force-exclude]
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.12.1
    hooks:
      - id: zizmor
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        files: ^doc/.*\.md$
        args: [-l 90]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-pyproject
          - mdformat-myst
          - mdformat-gfm
          - mdformat-gfm-alerts
          # - mdformat-ruff
          - mdformat-config
          - mdformat-deflist
        exclude: ^.github/.*\.md$
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.6.2
    hooks:
      - id: prettier
        args: ["--print-width", "120"]
        require_serial: true
        types_or: [yaml]
  - repo: https://github.com/cmhughes/latexindent.pl
    rev: V3.24.7
    hooks:
      - id: latexindent
        args: [-l, -m, -s, -wd]
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.2
    hooks:
      - id: biome-check
        types_or: [json, html, css]
        files: ".*" # Override default files regex that excludes html, rely on `types_or` instead
