exclude: ^.idea/|^conda/meta.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-json
        exclude: ^.vscode/
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.0
    hooks:
      - id: poetry-check
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.15.0
    hooks:
      - id: blacken-docs
        entry: bash -c "blacken-docs -l 90 $(find doc/ -name '*.md')"
        args: [ -l 90 ]
        additional_dependencies: [ black==23.3.0 ]
