# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --only-group doc --frozen
    - uv run -m sphinx -T -b html -d doc/_build/doctrees doc $READTHEDOCS_OUTPUT/html
