name: roseau-load-flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy >=1.21.5
  - pandas >=1.4.0,<2.0.0
  - geopandas >=0.10.2
  - shapely >=2.0.0
  - regex >=2022.1.18
  - pint >=0.19.2
  - requests >=2.28.1,<3.0.0
