name: roseau-load-flow
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy >=1.21.5
  - pandas >=1.4.0
  - geopandas >=0.10.2
  - shapely >=2.0.0
  - regex >=2022.1.18
  - pint >=0.21.0
  - requests >=2.28.1
  - typing_extensions >=4.6.2
  - rich >=13.5.1
  - pyproj >=3.3.0
  - matplotlib-base >=3.7.2
  - networkx >=3.0.0
