# prettier-ignore
{% set name = "roseau-load-flow" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../
#  url: ../dist/{{ name }}-{{ version }}.tar.gz
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
#  sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7


build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python
    - numpy >=1.21.5
    - poetry
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=1.4.0
    - geopandas >=0.10.2
    - shapely >=2.0.0
    - regex >=2022.1.18
    - pint >=0.21.0
    - requests >=2.28.1
    - typing-extensions >=4.6.2
    - rich >=13.5.1
    - matplotlib >=3.7.2

test:
  imports:
    - roseau
    - roseau.load_flow
    - roseau.load_flow.io
    - roseau.load_flow.models
    - roseau.load_flow.utils

about:
  home: https://github.com/RoseauTechnologies/Roseau_Load_Flow/
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Highly capable three-phase load flow solver of Roseau Technologies.
  doc_url: https://roseautechnologies.github.io/Roseau_Load_Flow/

extra:
  recipe-maintainers:
    - benoit9126

# https://www.underworldcode.org/articles/build-conda-packages/
# conda config --add channels conda-forge
# conda config --set channel_priority strict
# conda build conda
# conda install --use-local roseau_load_flow
