# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------
project = "SIRAO"
copyright = "2022, Roseau Technologies SAS"
# author = "Roseau Technologies SAS"

# The full version, including alpha/beta/rc tags
release = "v1.0.1"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["myst_parser", "sphinx_math_dollar", "sphinx.ext.mathjax"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "fr"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# Number the figures
numfig = False
numfig_format = {
    "figure": "",  # By default, "'Fig. %s',
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'
html_theme = "sphinx_book_theme"
html_show_copyright = True
html_theme_options = {
    "toc_title": "Sommaire",
    "repository_url": "https://github.com/RoseauTechnologies/SIRAO_Documentation_Dev/",
    "use_issues_button": False,
    "repository_branch": "main",
    "use_fullscreen_button": False,
    "logo_only": True,
    "use_download_button": False,
    "show_navbar_depth": 2,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = []

# Logo
# html_logo = "_static/SIRAO_Without_Baseline.svg"

# Favicon
# html_favicon = "_static/favicon.ico"

# Last updated footer
html_last_updated_fmt = "%x"

# Extra CSS files
html_css_files = ["https://fonts.googleapis.com/icon?family=Material+Icons"]
