name: CI

on:
  push:
    branches: [main, develop]
    tags:
      - "*"
    paths-ignore:
      - "doc/**"
      - ".vscode/**"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "doc/**"
      - ".vscode/**"

env:
  CI: true
  UV_SYSTEM_PYTHON: 1
  COVERAGE_CORE: sysmon

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14", "3.14t", "3.15", "3.15t"]

    permissions:
      contents: read

    steps:
      # TODO: remove once pyogrio publishes wheels for Python 3.15
      - name: Install GDAL to build pyogrio
        if: startsWith(matrix.python-version, '3.15')
        run: |
          sudo apt update
          sudo apt -yq --no-install-suggests --no-install-recommends install libgdal-dev

      - uses: actions/checkout@v7.0.1
        with:
          lfs: false
          persist-credentials: false

      - name: Git LFS
        uses: $/.github/actions/git-lfs

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          # TODO orjson (fast-json extra) has no wheels for free-threaded Python
          uv sync --frozen --all-extras \
            ${{ endsWith(matrix.python-version, 't') && '--no-extra fast-json' || '' }}

      - name: Test with pytest
        run: |
          uv run pytest -vv --durations=25 --cov --cov-report=html roseau
        env:
          ROSEAU_LOAD_FLOW_LICENSE_KEY: ${{ secrets.ROSEAU_LOAD_FLOW_LICENSE_KEY }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v7
        if: ${{ always() }}
        with:
          name: code-coverage-report-${{ runner.os }}-python-${{ matrix.python-version }}
          path: htmlcov/
