name: Conda

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]

env:
  CI: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Cache git LFS
        uses: actions/cache@v3
        with:
          path: .git/lfs
          key: git-lfs-v1-${{ matrix.python-version }}-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            git-lfs-v1-${{ matrix.python-version }}
            git-lfs-v1
            git-lfs

      - name: Git LFS
        run: |
          git lfs checkout
          git lfs pull
          git lfs prune --verify-remote

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda Build
        id: conda-build
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install --channel conda-forge conda-build conda-verify
          mkdir -p dist/
          conda build --output-folder dist/ conda/
          echo "CONDA_ARCHIVE=$(conda build --output-folder dist/ --output conda/)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package-python-${{ matrix.python-version }}
          path: ${{ steps.conda-build.outputs.CONDA_ARCHIVE }}
