name: pre-commit

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - ".vscode/**"
      - ".idea/**"
    tags:
      - "*"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - ".vscode/**"
      - ".idea/**"

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          lfs: false
          persist-credentials: false

      - name: Git LFS
        uses: $/.github/actions/git-lfs

      - uses: j178/prek-action@v3.0.0
